name: Build and test
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**Makefile'
      - '**.go'
      - '**.proto'
      - 'go.mod'
      - 'go.sum'
jobs:

  build-windows:
    name: Build Windows 386
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo $Env:GITHUB_REF.Substring(11)
          set GOARCH=386
          go env
          go build -trimpath -ldflags "-X main.Build=$($Env:GITHUB_REF.Substring(11))" -o build\nebula.exe ./cmd/nebula-service
          go build -trimpath -ldflags "-X main.Build=$($Env:GITHUB_REF.Substring(11))" -o build\nebula-cert.exe ./cmd/nebula-cert

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: windows-latest
          path: build

  test-linux:
    name: Build all and test on ubuntu-linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16-

    - name: Build
      run: make all

    - name: Test
      run: make test

    - name: End 2 end
      run: make e2evv

  test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.16-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.16-

    - name: Build nebula
      run: go build ./cmd/nebula

    - name: Build nebula-cert
      run: go build ./cmd/nebula-cert

    - name: Test
      run: go test -v ./...

    - name: End 2 end
      run: make e2evv
