name: Build windows 386
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/windows.yml'
      - '**Makefile'
      - '**.go'
      - '**.proto'
      - 'go.mod'
      - 'go.sum'
jobs:

  build-windows:
    name: Build Windows 386
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo $Env:GITHUB_REF.Substring(11)
          go.exe env -w GOARCH=386
          go env
          go build -trimpath -ldflags "-X main.Build=$($Env:GITHUB_REF.Substring(11))" -o build\nebula.exe ./cmd/nebula-service
          go build -trimpath -ldflags "-X main.Build=$($Env:GITHUB_REF.Substring(11))" -o build\nebula-cert.exe ./cmd/nebula-cert

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-latest
          path: build
